CLUSTAL multiple sequence alignment by MUSCLE (3.8)


Human_HBB                MVHLTPEEKSAVTALWGKVNVDEVGGEALGRLLVVYPWTQRFFESFGDLSTPDAVMGNPK
Channel_catfish          MVHWTDAERHIIADLWGKINHDEIGGQALARLLIVYPWTQRYFSSFGNLSNAAAIIGNPK
Anguillicola_globin      MVEWTDAEHTAILSLWKKINVEEIGPQAMRRLLIVCPWTQRHFANFGNLSTAAAIMNNEK
Eel                      -VEWTEDERTAIKSKWLKINIEEIGPQAMRRLLIVCPWTQRHFANFGNLSTAAAIMNNDK
Zebrafish                MVEWTDAERTAILGLWGKLNIDEIGPQALSRCLIVYPWTQRYFATFGNLSSPAAIMGNPK
Atlantic_salmon          MVDWTDAERSAIVGLWGKISVDEIGPQALARLLIVSPWTQRHFSTFGNLSTPAAIMGNPA
Rainbow_trout            MVDWTDPERSAIVGLWGKISVDEIGPQALARLLIVSPWTQRHFSTFGNLSTPAAIMGNPA
                          *  *  *.  :   * *:. :*:* :*: * *:* *****.* .**:**.. *::.*  

Human_HBB                VKAHGKKVLGAFSDGLAHLDNLKGTFATLSELHCDKLHVDPENFRLLGNVLVCVLAHHFG
Channel_catfish          VAAHGKVVLGGLTKAVQNLDNIKGIYTQLSTLHSEKLHVDPSNFTLLGDTFTVTLAANFG
Anguillicola_globin      VAKHGTTVMGGLDRAIQNMDDIKNAYRELSVMHSEKLHVDPDNFRLLSEHITLCMAAKFG
Eel                      VAKHGTTVMGGLDRAIQNMDDIKNAYRQLSVMHSEKLHVDPDNFRLLAEHITLCMAAKFG
Zebrafish                VAAHGRTVMGGLERAIKNMDNVKNTYAALSVMHSEKLHVDPDNFRLLADCITVCAAMKFG
Atlantic_salmon          VAKHGKTVMHGLDRAVQNLDDIKNAYTALSVMHSEKLHVDPDNFRLLADCITVCVAAKLG
Rainbow_trout            VAKHGKTVMHGLDRAVQNLDDIKNTYTALSVMHSEKLHVDPDNFRLLADCITVCVAAKLG
                         *  **  *: .:  .: ::*::*. :  ** :*.:******.** **.: :.   * ::*

Human_HBB                KE-FTPPVQAAYQKVVAGVANALAHKYH
Channel_catfish          PSVFTPEVHETWQKFLNVVVAALGKQYH
Anguillicola_globin      PTEFTADVQEAWQKFLMAVTSALGRQYH
Eel                      PTEFTADVQEAWQKFLMAVTSALARQYH
Zebrafish                QAGFNADVQEAWQKFLAVVVSALCRQYH
Atlantic_salmon          PTVFSADIQEAFQKFLAVVVSALGRQYH
Rainbow_trout            PAVFSADTQEAFQKFLAVVVSALGRQYH
                            *..  : ::**.:  *. ** .:**
